In [13]:
import re, os, sys
from functools import reduce
from itertools import combinations as comb, permutations as perm, combinations_with_replacement as combr
from operator import itemgetter
from pprint import pprint
from math import *
from collections import defaultdict
import networkx as nx
import numpy as np
from itertools import pairwise

def dprint(d):
    pprint(dict(d))
def lmap(*args, **kwargs):
    return list(map(*args, **kwargs))
def lmapi(*args, **kwargs):
    return list(map(int, *args, **kwargs))
def enum(*args, **kwargs):
    return enumerate(*args, **kwargs)

In [91]:
input_fname = "../inputs/day14-demo.in"

In [111]:
input_fname = "../inputs/day14.in"

In [112]:
def reread():
    lines = []
    with open(input_fname) as ifile:
        def r(): return ifile.readline().strip()
        def rs(): return ifile.readline().strip().split()
        def ri(): return int(ifile.readline().strip())
        def ris(): return list(map(int, ifile.readline().strip().split()))

        minx = maxx = miny = maxy = 0
        for line in ifile:
            pts = line.strip().split(" -> ")
            pts = [lmapi(pt.split(",")) for pt in pts]
            lines.append(pts)

        minx = min(min(map(itemgetter(0), pts)) for pts in lines) - 1
        miny = 0 #min(min(map(itemgetter(1), pts)) for pts in lines)
        maxx = max(max(map(itemgetter(0), pts)) for pts in lines) + 1
        maxy = max(max(map(itemgetter(1), pts)) for pts in lines) + 1

        # print(minx, maxx, miny, maxy)

        rangex = maxx - minx + 1
        rangey = maxy - miny + 1
        ar = np.zeros((rangey, rangex), dtype=int)

        for pts in lines:
            for (x1, y1), (x2, y2) in pairwise(pts):
                x1, x2 = min(x1, x2), max(x1, x2)
                y1, y2 = min(y1, y2), max(y1, y2)
                x1, y1, x2, y2 = x1 - minx, y1 - miny, x2 - minx, y2 - miny
                # print(y1,y2+1,x1,x2+1)
                ar[y1:y2+1,x1:x2+1] = 1
                # print(ar)
                # break
        print(ar)

    origx = 500 - minx
    print(origx)
    return ar, origx

ar, origx = reread()
# lines[:10]

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
11


## Part 1

In [102]:
fall = ar.copy()
ct = 0
done = False
while ct < 1000 and not done:
    ct += 1
    curx, cury = origx, 0
    while True:
        if max(fall[cury:,curx]) == 0:
            print("done at", ct-1)
            done = True
            break
        blocky = cury + np.argmax(fall[cury:,curx])
        if fall[blocky,curx-1] == 0:
            curx, cury = curx-1, blocky
        elif fall[blocky,curx+1] == 0:
            curx, cury = curx+1, blocky
        else:
            fall[blocky-1,curx] = 1
            break
    # break
print(fall+ar)

done at 24
[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 0 0 0]
 [0 0 0 0 0 2 1 1 1 2 2 0]
 [0 0 0 0 1 2 1 1 1 2 0 0]
 [0 0 0 2 2 2 1 1 1 2 0 0]
 [0 0 0 0 0 1 1 1 1 2 0 0]
 [0 0 1 0 1 1 1 1 1 2 0 0]
 [0 2 2 2 2 2 2 2 2 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]


24

## Part 2

In [113]:
nr, nc = ar.shape
ar2 = np.zeros((nr+1, nc), dtype=int)
ar2[:nr,] = ar
pad = nr
norigx = origx + pad
ar2 = np.pad(ar2, [(0,0), (pad, pad)])
ar2[-1,] = 1
print(ar2)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]


In [119]:
fall = ar2.copy()
ct = 0
done = False
while ct < 50000 and not done and min(fall[1,norigx-1:norigx+2])==0:
    ct += 1
    curx, cury = norigx, 0
    while True:
        if max(fall[cury:,curx]) == 0:
            print("done at", ct-1)
            done = True
            break
        blocky = cury + np.argmax(fall[cury:,curx])
        if fall[blocky,curx-1] == 0:
            curx, cury = curx-1, blocky
        elif fall[blocky,curx+1] == 0:
            curx, cury = curx+1, blocky
        else:
            fall[blocky-1,curx] = 1
            break
    # break
print(fall+ar2)
print(ct+1)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [2 2 2 ... 2 2 2]]
25434
